spring:
  application:
    name: api-gateway

zuul:
  routes:
    user-service:
      path: /users/**
      url: http://localhost:8081
      strip-prefix: false

    order-service:
      path: /orders/**
      url: http://localhost:8082
      strip-prefix: false

management:
  endpoints:
    web:
      exposure:
        include: routes